
import Link from 'next/link'
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { ArrowLeft, ShieldCheck, Lock, Eye, Server } from 'lucide-react'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Learn how MinifyLinks collects, uses, and protects your data. We prioritize transparency and user privacy.",
  alternates: {
    canonical: "/privacy",
  },
};

export default function PrivacyPolicy() {
  const lastUpdated = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  })

  return (
    <div className="min-h-screen bg-white py-12 px-4 sm:px-6 lg:px-8 text-slate-900">
      
      {/* Navigation */}
      <div className="max-w-4xl mx-auto mb-4">
        <Link href="/">
          <Button variant="ghost" className="text-slate-500 hover:text-blue-500 hover:bg-white pl-0">
            <ArrowLeft className="w-4 h-4 mr-2" /> Back to Home
          </Button>
        </Link>
      </div>

      <div className="max-w-5xl mx-auto space-y-8">
        
        {/* Header */}
        <div className="text-center space-y-4">
          <div className="mx-auto w-12 h-12 bg-blue-100 rounded-full flex items-center justify-center mb-4">
            <ShieldCheck className="w-6 h-6 text-blue-600" />
          </div>
          <h1 className="text-4xl font-black font-semibold tracking-tight text-slate-900">Privacy Policy</h1>
          <p className="text-slate-500">Last updated: {lastUpdated}</p>
        </div>

        {/* Content Card */}
        <Card className=" border-none bg-white py-0">
          <CardContent className="p-8 md:p-12 space-y-10">
            
            {/* Introduction */}
            <section className="space-y-3">
              <h2 className="text-xl font-bold flex items-center gap-2">
                1. Introduction
              </h2>
              <p className="text-gray-600 leading-relaxed">
                Welcome to <strong>MinifyLinks</strong> (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;). We are committed to protecting your privacy while you use our URL shortening and redirection service. 
                This Privacy Policy explains how we collect, use, and safeguard information when you access our short links or use our dashboard.
              </p>
            </section>

            <hr className="border-gray-100" />

            {/* Information Collection */}
            <section className="space-y-4">
              <h2 className="text-xl font-bold flex items-center gap-2">
                <Eye className="w-5 h-5 text-blue-500" /> 2. Information We Collect
              </h2>
              <p className="text-gray-600 leading-relaxed">
                When you click on a short link generated by our service, our servers automatically record certain information (&quot;Log Data&quot;). This data is used solely for analytics and fraud prevention.
              </p>
              <ul className="list-disc pl-5 space-y-2 text-gray-600">
                <li><strong>Device Information:</strong> We collect details about the device and browser you use (e.g., Chrome on iPhone) to optimize the redirection experience.</li>
                <li><strong>IP Address & Location:</strong> We use your IP address to derive a general geographic location (Country/City). We do not store precise GPS coordinates.</li>
                <li><strong>Referrer Data:</strong> We may record the website or platform you came from before clicking the link.</li>
                <li><strong>Time of Access:</strong> The date and time of your click.</li>
              </ul>
              <div className="bg-blue-50 p-4 rounded-lg border border-blue-100 text-sm text-blue-800">
                <strong>Note on Data Sampling:</strong> To minimize data retention, we do not store detailed logs for every single visitor. Our system captures a random statistical sample (approximately 10%) of traffic for demographic analysis.
              </div>
            </section>

            <hr className="border-gray-100" />

            {/* Usage */}
            <section className="space-y-3">
              <h2 className="text-xl font-bold flex items-center gap-2">
                <Server className="w-5 h-5 text-blue-500" /> 3. How We Use Your Data
              </h2>
              <p className="text-gray-600 leading-relaxed">
                We use the collected information for the following specific purposes:
              </p>
              <ul className="list-disc pl-5 space-y-2 text-gray-600">
                <li>To provide accurate redirection to the target destination.</li>
                <li>To generate aggregated, non-identifiable statistics for our link administrators (e.g., &quot;50% of visitors are from the USA&quot;).</li>
                <li>To identify and block malicious bots, spam, or abusive traffic patterns.</li>
              </ul>
            </section>

            <hr className="border-gray-100" />

            {/* Cookies */}
            <section className="space-y-3">
              <h2 className="text-xl font-bold flex items-center gap-2">
                <Lock className="w-5 h-5 text-blue-500" /> 4. Cookies & Caching
              </h2>
              <p className="text-gray-600 leading-relaxed">
                <strong>Visitor Tracking:</strong> We do not set persistent tracking cookies on the devices of visitors who simply click our links.
              </p>
              <p className="text-gray-600 leading-relaxed">
                <strong>Browser Caching:</strong> To improve performance, we instruct your browser to cache the redirect destination for up to 24 hours. This means subsequent clicks on the same link may be handled entirely by your browser without contacting our servers.
              </p>
            </section>

            <hr className="border-gray-100" />

            {/* Contact */}
            <section className="space-y-3">
              <h2 className="text-xl font-bold">5. Contact Us</h2>
              <p className="text-gray-600">
                If you have questions about this privacy policy, please contact us at:
              </p>
              <p className="font-medium text-slate-900 hover:underline hover:text-blue-500">support@minifylinks.com</p>
            </section>

          </CardContent>
        </Card>
      </div>
    </div>
  )
}